local mission = {
    name = "Synd",
    pedInteractLabel = "Tryck på E",
    missionsRequire = "Marcus",
    cooldownTime = 1, -- 1 minut cooldown
    pedModel = "S_M_M_Trucker_01",
    pedCoords = vector4(-1801.99, 2966.01, 32.81, 62.33),
    icon = "fas fa-sign-in-alt",
    label = "Öppna",
    pedSpeech = "Test Synd!",
    pedtitle = "Synd!!",
    pedLabelAccept = "Ja! Test",
    pedLabelDeny = "Nej! Test",
    pedAcceptReaction = "GENERIC_THANKS",
    pedDenyReaction = "GENERIC_CURSE_HIGH",
    description = "Get to the location 1",
    pedAcceptSound = "jail",
    pedAcceptSoundDistance = 2,
    pedAcceptSoundVolume = 2,
    pedDenySound = "jail",
    pedDenySoundDistance = 2,
    pedDenySoundVolume = 2,
    pedGreetingSound = "blackmarker_quest",
    BannedJobsAndGangs = {
        jobs = {"police", "ambulance"},
        gangs = {""}
    },
    tasks = {
        {
            description = "~b~Get to the location 2",
            coords = vector3(-1805.15, 2981.96, 32.81),
            waitTime = 0,
            playSound = "jail",
            distance = 0.5,
            volume = 2,
            ExecuteCommand = "e pickup",
            spawnVehicle = "t20",
            spawnVehicleCoords = vector4(-1812.08, 2981.84, 32.39, 59.53),
            MarkerTitel = "~w~[~b~E~w~] Tryck",
            markerRadius = 5,
            interactKeyRadius = 2,
            MarkertType = 6,
            MarkertBob = true,
            MarkertRotate = true,
            MarkertR = 0,
            MarkertG = 0,
            MarkertB = 153,
            MarkertSize = vector3(1, 1, 1),
            rotX = -90.0,
            rotY = 180.0,
            rotZ = 0.0
        },
        {
            description = "Get to the location 3",
            coords = vector3(-1812.33, 2986.17, 32.81),
            waitTime = 0,
            ExecuteCommand = "e pickup",
            MarkerTitel = "~w~[~b~E~w~] Tryck",
            markerRadius = 5,
            interactKeyRadius = 2,
            MarkertType = 6,
            MarkertBob = true,
            MarkertRotate = true,
            MarkertR = 50,
            MarkertG = 256,
            MarkertB = 0,
            MarkertSize = vector3(1, 1, 1),
            rotX = -90.0,
            rotY = 180.0,
            rotZ = 0.0,
            customtrigger = "setfire"
        },
        {
            description = "Klar 2",
            coords = vector3(-1820.37, 2989.69, 32.81),
            waitTime = 0,
            playSound = "jail",
            distance = 0.5,
            volume = 2,
            deleteVehicle = true,
            MarkerTitel = "~w~[~b~E~w~] Tryck",
            markerRadius = 5,
            interactKeyRadius = 2,
            MarkertType = 6,
            MarkertBob = true,
            MarkertRotate = true,
            MarkertR = 50,
            MarkertG = 256,
            MarkertB = 0,
            MarkertSize = vector3(1, 1, 1),
            rotX = -90.0,
            rotY = 180.0,
            rotZ = 0.0,
            addItem = "lockpick",
            addItemAmount = 1,
            addCash = 100,
            addBank = 1000,
            rewards = "1"
        }
    }
}

table.insert(Config.Missions, mission)